### ISSUE TITLE
导入swing,imageio报错

### ISSUE THREAD

**Issue by shenqierbufan** [ljy1058318852/ocrIdentify#1]
Bp版本2022，jdk11，jpython环境：jpython2.7/最新的jpython，都进行过尝试，都报这个错误
![](https://user-images.githubusercontent.com/71680430/267028470-7ebd0c2d-c772-4938-bbf3-997f0469cad8.png)

**Comment by potato-security** [comment]
python请选择python2（Bp只支持python2环境），如果还报错，请尝试使用python2对应的pip install imageio

如果还存在问题请留言
